export const TECH_ICON_COLORS: Record<string, string> = {
  react: "text-cyan-400",
  reactNative: "text-sky-400",
  next: "text-slate-100",
  typescript: "text-blue-500",
  vue: "text-emerald-400",
  node: "text-green-500",
  express: "text-slate-100",
  dotnet: "text-violet-500",
  python: "text-blue-400",
  go: "text-cyan-300",
  postgresql: "text-blue-500",
  mongodb: "text-green-500",
  redis: "text-red-500",
  oracle: "text-red-500",
  sqlServer: "text-rose-400",
  docker: "text-blue-500",
  aws: "text-orange-400",
  azure: "text-blue-500",
  railway: "text-purple-400",
  githubActions: "text-blue-500",
};